{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "langprobe.fullname" . }}
  labels:
    {{- include "langprobe.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- with .Values.ingress.hosts.web }}
    {{- if .host }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "langprobe.web.fullname" $ }}
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.hosts.api }}
    {{- if .host }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "langprobe.api.fullname" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- with .Values.ingress.hosts.ingest }}
    {{- if .host }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "langprobe.ingestApi.fullname" $ }}
                port:
                  number: {{ $.Values.ingestApi.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
